### ISSUE TITLE
Test the model

### ISSUE THREAD

**Issue by Ayanzadeh93** [Con-Mi/PhaseContrast-Segementation#1]
Dear Author, 

I have an important question about your prepared model. How we can test the model performance.  I train the model with mGpuoptimization.py and made the checkpoint after training process. So, now how can I test the model performance for testest.

**Comment by Con-Mi** [comment]
Hey,

Thanks for the interest. If you have run the optimization loop in the script, this will output and save a
protobuf in your system named
```
dense_linknet_512_sgd_bce.pt
```

Then you can use the following
``` 
import torch
from helper import load_model
from LinkNetModel import DenseLinkModel
from torchvision import transforms
from PIL import Image


BIN_PATH  = "../../binaries/dense_linknet_512_sgd_bce.pt"

segm_model = DenseLinkModel(input_channels=1, num_classes=3)
segm_model = load_model(segm_model, model_dir=BIN_PATH)

img = tsfm(img)
img = img.unsqueeze(dim=0)
tsfm = transforms.Compose([transforms.Resize((img_size, img_size)) , transforms.ToTensor()])
img = Image.open(IMG_PATH).convert("L")

out = segm_model(img)
```

Check the 
```
inference.py
```
 script that I have. Running it will plot the result on an image (customize the directory of the image and binary of the model). Please bare in mind that I have tested this on some data that I had, but I did not get that great results. 

Let me know if something doesnt work for you.

**Comment by Ayanzadeh93** [comment]
Thank you so much for your consideration. I checked the code and faced with errors which I want to put it below,

--------------------------------------------------------------------------
NameError   Traceback (most recent call last)
<ipython-input-7-e6e92b40167d> in <module>
     11 segm_model = load_model(segm_model, model_dir=BIN_PATH)
     12 
---> 13 img = tsfm(img)
     14 img = img.unsqueeze(dim=0)
     15 tsfm = transforms.Compose([transforms.Resize((img_size, img_size)) , transforms.ToTensor()])

NameError: name 'tsfm' is not defined


I install the quoted one with pip, but I faced with determined error yet.

**Comment by Con-Mi** [comment]
Checking your code it seems that you are using the
``` 
img = tsfm(img)
```
before defining tsfm.
First define the image transforms from torchvision and then run it on the image.
ie,
```
trnsfm =  transforms.Compose([transforms.Resize((img_size, img_size)) , transforms.ToTensor()])
img = trnsfm(img)
img = img.unsqueeze(dim=0)
```
